version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing minimal dependencies for pipeline trigger"
      - pip install --upgrade pip
      - pip install sagemaker==2.210.0
      - pip install boto3==1.28.17
      - pip install pydantic==2.5.0
      - python -c "import sagemaker, boto3; print('Core packages ready')"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - aws sts get-caller-identity
      
  build:
    commands:
      - echo "Build phase started"
      - echo "Executing OLINK classification pipeline"
      - python scripts/trigger.py
        
  post_build:
    commands:
      - echo "Post-build phase completed"
      
artifacts:
  files:
    - '**/*'
  base-directory: '.'