version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running training script on Sagemaker..."
      - python run_sagemaker.py

artifacts:
  files:
    - results/*
    - results/plots/*
  discard-paths: no
